# Generated by Django 6.0.4 on 2026-04-19 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Tech & AI", "Tech & AI"),
                            ("Business & Startup", "Business & Startup"),
                            ("Entertainment", "Entertainment"),
                            ("Space & Science", "Space & Science"),
                            ("Weird Ideas", "Weird & Crazy Ideas"),
                            ("Sports & Fitness", "Sports & Fitness"),
                            ("Education", "Education"),
                            ("Others", "Others"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Beginner", "Beginner"),
                            ("Epic", "Epic"),
                            ("Legendary", "Legendary"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PathStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("estimated_time", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("In Progress", "In Progress"),
                            ("Completed", "Completed"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="dreams.dream",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
