# Generated by Django 6.0.4 on 2026-04-20 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dreams", "0002_user_alter_dream_options_alter_pathstep_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dream",
            name="user",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
